platform :ios, '8.0'
use_frameworks!

target 'ox-push2-ios-pod_Example' do
  #pod 'ox-push2-ios-pod'
  pod  'ox-push3', :path => '/Users/nazaryavornytskyy/ox-push2-ios-pod'
  pod 'AFNetworking'
  pod 'NSHash'
  pod 'NHNetworkTime'
  pod 'QRCodeReaderViewController', '~> 4.0.1'
  pod 'SCLAlertView-Objective-C'

end
